TASKS:
  # example_task_20hsv:
  #   input_rna: /lustre/groups/ml01/workspace/eirini/heerenlab_data/rna_model_preprocessed.h5ad
  #   input_metabolomics: /lustre/groups/ml01/workspace/eirini/heerenlab_data/msi_model_preprocessed_spatial_hv_top20_only.h5ad
  #   split: split_random_80_20
  #   methods:
  #     ridge:
  #       params: params/ridge_params.tsv
  #     lasso:
  #       params: params/lasso_params.tsv
  #     linear:
  #       params: params/linreg_params.tsv
  #     elastic_net:
  #       params: params/elastic_net_params.tsv
  #     xgboost:
  #       params: params/xgboost_params.tsv

  # rna_msi_hvg_baseline:
  #   input_rna: /lustre/groups/ml01/workspace/eirini/heerenlab_data/rna_model_preprocessed.h5ad
  #   input_metabolomics: /lustre/groups/ml01/workspace/eirini/heerenlab_data/msi_model_preprocessed_hvg_metabolites.h5ad
  #   split: split_random_80_20
  #   methods:
  #     ridge:
  #       params: params/ridge_params.tsv
  #     lasso:
  #       params: params/lasso_params.tsv
  #     linear:
  #       params: params/linreg_params.tsv
  #     elastic_net:
  #       params: params/elastic_net_params.tsv
  #     xgboost:
  #       params: params/xgboost_params.tsv
  
  # msi_to_rna_poc:
  #   input_rna: /lustre/groups/ml01/workspace/eirini/heerenlab_data/msi_model_preprocessed.h5ad
  #   input_metabolomics: /lustre/groups/ml01/workspace/eirini/heerenlab_data/rna_model_preprocessed.h5ad
  #   split: split_random_80_20
  #   methods:
  #     ridge:
  #       params: params/ridge_params.tsv
  #     lasso:
  #       params: params/lasso_params.tsv
  #     linear:
  #       params: params/linreg_params.tsv
  #     elastic_net:
  #       params: params/elastic_net_params.tsv
  #     xgboost:
  #       params: params/xgboost_params.tsv

  rna_to_msi_full:
    input_rna: /lustre/groups/ml01/workspace/eirini/heerenlab_data/rna_model_preprocessed.h5ad
    input_metabolomics: /lustre/groups/ml01/workspace/eirini/heerenlab_data/msi_model_preprocessed.h5ad
    split: split_random_80_20
    methods:
      ridge:
        params: params/ridge_params.tsv
      lasso:
        params: params/lasso_params.tsv
      linear:
        params: params/linreg_params.tsv
      elastic_net:
        params: params/elastic_net_params.tsv
      xgboost:
        params: params/xgboost_params.tsv
  
